version: "3.7"
services:
  server:
    build: ..
    ports:
      - "53:53/udp"
    volumes:
      - ./var_named:/var/named
      - ./named.conf:/etc/named.conf
    environment:
      - NAMEDCONF=/etc/named.conf
      - LOG_LEVEL=5


